version: "3.8"
services:
  db:
    container_name: postgres_workout
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: workout
      POSTGRES_USER: workout
      POSTGRES_DB: workout
    ports:
      - "5432:5432"
    restart: always
    #volumes:
    #  - 'postgres:/data/postgres'
    #network:
    #  - db-postgres